spring.application.name=hospital-management

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=RadhaKrishna@2923

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Spring Security (optional, remove if not needed)
spring.security.user.name=root
spring.security.user.password=RadhaKrishna@2923

# Server port (ensure free)
server.port=5500